`timescale 1ns / 10ps

//GENERATED BY AI, NOT WRITTEN BY ME

module sram_bank_wrapper #(
    parameter ADDR_WIDTH = 11,
    parameter DATA_WIDTH = 4096 
)(
    input  logic clk,
    // Port A: Read/Write (Host DMA)
    input  logic [ADDR_WIDTH-1:0]  addr_a,
    input  logic [DATA_WIDTH-1:0]  data_in_a,
    input  logic                   we_a,
    input  logic                   en_a,
    output logic [DATA_WIDTH-1:0]  data_out_a,

    // Port B: Read Only (TPU MXU)
    input  logic [ADDR_WIDTH-1:0]  addr_b,
    input  logic                   en_b,
    output logic [DATA_WIDTH-1:0]  data_out_b
);

`ifndef SYNTHESIS
    // ==========================================
    // SIMULATION BEHAVIORAL MODEL (For Verilator)
    // ==========================================
    
    // The core memory array
    logic [DATA_WIDTH-1:0] ram [0:(1<<ADDR_WIDTH)-1];

    // Optional: Pre-load weights for your testbench
    // Comment this out if you want to test the DMA writing logic instead
    initial begin
        // $readmemh("weights_layer_1.hex", ram);
    end

    // Port A (Read/Write) - Synchronous!
    always_ff @(posedge clk) begin
        if (en_a) begin
            if (we_a) begin
                ram[addr_a] <= data_in_a;
            end
            data_out_a <= ram[addr_a]; 
        end
    end

    // Port B (Read Only) - Synchronous!
    always_ff @(posedge clk) begin
        if (en_b) begin
            data_out_b <= ram[addr_b];
        end
    end

`else
    // ==========================================
    // PHYSICAL ASIC MACRO 
    // ==========================================
    
    /* Uncomment and instantiate your generated macro here later:
    
    TSMC_SRAM_DP_MACRO u_physical_sram (
        .CLK(clk),
        .ADDRA(addr_a), .DINA(data_in_a), .WEA(we_a), .ENA(en_a), .DOUTA(data_out_a),
        .ADDRB(addr_b), .ENB(en_b), .DOUTB(data_out_b)
    );
    */
`endif

endmodule